auth0:
  audience: https://learning-auth0/spring
spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://dev-9bgfkzlho.eu.auth0.com/

logging:
  level:
    root: INFO
    com: DEBUG